// packages/solid/src/index.ts
import { createResource } from 'solid-js';
import { createTranslator } from 'intl-schematic';
import { Plugin } from 'intl-schematic/plugins';

export interface LocaleResponse<Locale> {
  default: Locale;
  remote?: Promise<Locale | undefined>;
}

export function createLocaleResource<P extends readonly Plugin[]>(
  getLocale: () => Intl.Locale | Promise<Intl.Locale>,
  plugins: (locale: () => Intl.Locale) => P,
) {
  return <LocaleDoc extends Record<string, any>>(
    localeImport: (lang: Intl.Locale) => Promise<LocaleResponse<LocaleDoc>>,
  ) => {
    const [localeResource, { mutate }] = createResource(
      getLocale,
      (localePromise) => Promise.resolve(localePromise)
        .then(loc => Promise.all([localeImport(loc), loc] as const))
        .then(([localeDoc, locale]) => {
          localeDoc.remote?.then(loc => {
            if (loc) {
              mutate(([prev, prevLocale] = [localeDoc.default, locale]) => (
                [{ ...prev, ...loc }, prevLocale]
              ));
            }
          });

          return [localeDoc.default, locale] as const;
        })
    );

    const currentLocale = () => localeResource.latest?.[1] ?? new Intl.Locale(navigator.language);
    const currentDoc = () => localeResource.latest?.[0];

    return createTranslator(currentDoc, plugins(currentLocale));
  };
}

// packages/react/src/index.ts
import { useRef, useEffect, RefObject, useMemo } from 'react';
import { createTranslator } from 'intl-schematic';
import { Plugin } from 'intl-schematic/plugins';

export interface LocaleResponse<Locale> {
  default: Locale;
  remote?: Promise<Locale | undefined>;
}

export function createEffectTranslator<P extends readonly Plugin[]>(
  locale: RefObject<Intl.Locale | undefined>,
  plugins: (getLocale: () => Intl.Locale | undefined) => P,
) {
  return <LocaleDoc extends Record<string, any>>(
    localeImport: (lang: Intl.Locale) => Promise<LocaleResponse<LocaleDoc>>,
  ) => {
    const localeDoc = useRef<LocaleDoc>();

    useEffect((lang = locale?.current) => {
      if (!lang) {
        return;
      }

      localeImport(lang).then(val => {
        localeDoc.current = val.default;

        val.remote?.then(remote => {
          if (remote) {
            localeDoc.current = {
              ...localeDoc.current,
              ...remote,
            };
          }
        })
      });
    }, [locale]);

    const currentLocale = () => locale.current ?? new Intl.Locale(navigator.language);
    const currentDoc = () => localeDoc.current;

    return createTranslator(currentDoc, plugins(currentLocale));
  };
}
